apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-1-deployer
  namespace: team-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-1-full-access
  namespace: team-1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-1-full-access
  namespace: team-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: team-1-full-access
subjects:
- kind: ServiceAccount
  name: team-1-deployer
  namespace: team-1